# Generated by Django 4.2.1 on 2024-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер курса')),
                ('main_name', models.CharField(max_length=50, verbose_name='Название курса')),
                ('extra_name', models.CharField(max_length=50, verbose_name='Дополнительное название')),
                ('cost', models.IntegerField(verbose_name='Цена курса')),
                ('duration', models.IntegerField(verbose_name='Продолжительность курса')),
                ('lessons_num', models.IntegerField(verbose_name='Количество занятий')),
                ('description', models.TextField(verbose_name='Описание')),
                ('course_includes', models.TextField(verbose_name='Курс включает')),
                ('event_form', models.CharField(max_length=30, verbose_name='Форма проведения')),
                ('issue', models.CharField(max_length=30, verbose_name='Выдается')),
                ('big_img', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Большое изображениме')),
                ('mid_img', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Среднее изображениме')),
                ('small_img', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Маленькое изображениме')),
            ],
        ),
    ]
