# Generated by Django 4.2.1 on 2024-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='event_type',
            field=models.CharField(choices=[('И', 'Индивидуальное'), ('Г', 'Групповое'), ('ИГ', 'Индивидуальное/групповое')], default='null', max_length=30, verbose_name='Тип проведения'),
        ),
    ]
